<?php
/**
 * Created by PhpStorm.
 * User: nnikitchenko
 * Date: 13.05.2016
 */

namespace frontend\components;

use yii\web\Controller;

class WebController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->getView()->title = \Yii::$app->params['baseTitle'];
    }

}