<?php
/**
 * Created by PhpStorm.
 * User: nnikitchenko
 * Date: 23.05.2016
 */

namespace common\components;


use common\models\model\BookmakerSettings;
use common\models\SettingsCurrency;
use yii\base\Component;
use yii\di\Container;
use yii\web\HttpException;

class Settings extends Component
{
    /** @var Container */
    protected $container;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $container = new Container();

        $container->setSingleton('bookmaker_settings', function ($container, $params, $config) {
            return BookmakerSettings::all();
        });

        $container->setSingleton('currency_settings_kr', function ($container, $params, $config) {
            $obj = SettingsCurrency::find()
                ->andWhere('currency_type = :currency_type', [':currency_type' => SettingsCurrency::CURRENCY_KR])
                ->one();

            if($obj === null) {
                throw new HttpException(404);
            }

            return $obj;
        });

        $container->set('currency_settings_ekr', function ($container, $params, $config) {
            $obj = SettingsCurrency::find()
                ->andWhere('currency_type = :currency_type', [':currency_type' => SettingsCurrency::CURRENCY_EKR])
                ->one();

            if($obj === null) {
                throw new HttpException(404);
            }

            return $obj;
        });

        $this->container = $container;
    }

    /**
     * @return BookmakerSettings
     * @throws \yii\base\InvalidConfigException
     */
    public function book()
    {
        return $this->container->get('bookmaker_settings');
    }

    /**
     * @param $currency_type
     * @return SettingsCurrency
     * @throws \Exception
     * @throws \yii\base\InvalidConfigException
     */
    public function currency($currency_type)
    {
        $Currency = null;
        if($this->container->hasSingleton('currency_settings_'.$currency_type)) {
            $Currency = $this->container->get('currency_settings_'.$currency_type);
        }
        if(!$Currency) {
            throw new \Exception;
        }

        return $Currency;
    }
}